version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - cqrs_net

  cqrs-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cqrs_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  command-service:
    build: ./command-service
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
      POSTGRES_URL: ${POSTGRES_URL}
      SYNC_INTERVAL_MS: ${SYNC_INTERVAL_MS}
      COMMAND_PORT: ${COMMAND_PORT}
    expose:
      - "3001"
    labels:
      - traefik.docker.network=coolify
      - traefik.http.services.command-service.loadbalancer.server.port=3001
    depends_on:
      cqrs-postgres:
        condition: service_healthy
    networks:
      - cqrs_net
      - coolify

  query-service:
    build: ./query-service
    restart: unless-stopped
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      QUERY_PORT: ${QUERY_PORT}
    expose:
      - "3002"
    labels:
      - traefik.docker.network=coolify
      - traefik.http.services.query-service.loadbalancer.server.port=3002
    depends_on:
      cqrs-postgres:
        condition: service_healthy
    networks:
      - cqrs_net
      - coolify

volumes:
  mongo_data:
  postgres_data:

networks:
  cqrs_net:
    driver: bridge
  coolify:
    external: true
